Name = input("Name :")
Age  = int(input("Age :"))
Price = float(input("Price :"))
items = input("Items :")
Coupons =input("Coupons")
Address=input("Address")
Order = input("Order :")
print(Name)
print(Age)
print(Price)
print(items)
print(Coupons)
print(Address)
print(Order)
             
